# Generated by Django 3.2.4 on 2023-01-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('director', 'director'), ('writer', 'writer'), ('actor', 'actor')], default='actor', max_length=8, verbose_name='role'),
        ),
    ]
